apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dspm-ingress
  namespace: dspm
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dspm.techd.com
        - api.dspm.techd.com
      secretName: dspm-tls
  rules:
    - host: api.dspm.techd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dspm-backend
                port:
                  number: 8000
    - host: dspm.techd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dspm-frontend
                port:
                  number: 3000
